//! 无头 dsh（DeepSeek Harness，`dsh --profile headless`）适配器。
//!
//! 与 Claude / OpenCode / Codex 适配器同形、复用同一套 [`CodingAgentRequest`] /
//! [`CodingAgentEvent`] / [`CodingAgentError`]。但 dsh 的 CLI 面比另外三家窄得多，
//! 所以这个适配器多做了一件事：**给 dsh 挂一个自带的输出插件**。
//!
//! # 为什么要挂插件
//!
//! `dsh --profile headless "<任务>"` 只在结束时往 stdout 打一行最终文本——没有 JSON、
//! 没有逐字流、没有工具事件。但这不是 dsh 缺数据，而是 headless 这个 bundle 把过程
//! **汇总完就丢了**：它内部的会话事件总线上，`assistant/chunk`（含 text-delta）、
//! `tool/call`、`tool/result`、`turn/end` 一应俱全。
//!
//! dsh 是插件栈（cordis）架构，profile 由一层层 patch 叠成，`--patch <file>` 就是官方
//! 留给外部叠自己那层的入口。我们用它挂上 [`TAP_PLUGIN_JS`]——那是
//! [dsh-jsonl](https://github.com/bigsongeth/dsh-jsonl) 的一份逐字副本：一个订阅
//! `session/event` 的插件，把事件按有版本的公开 schema 打成 NDJSON 到 **stderr**，
//! stdout 的「只打最终文本」契约原样不动。
//!
//! # 上游耦合都收在那个 JS 里
//!
//! dsh 目前是 `0.1.0-rc.6`，事件形状还会变，而上游不收 PR，跟随成本由我们自己背。
//! 所以耦合点被压缩到那一个 JS 文件里：它把 dsh 的内部事件翻译成 dsh-jsonl 的公开 schema
//! （`text.delta` / `tool.call` / `turn.end` …），Rust 侧只认那个 schema。上游改字段时改
//! JS 即可，Rust 的解析和单测都不用动。
//!
//! 那个 JS 的源头在 dsh-jsonl 仓库，本仓库存的是带版本标记的副本，用
//! `scripts/vendor-dsh-jsonl.sh` 同步——**跨仓库没有自动同步**，见 [`TAP_PLUGIN_JS`]。
//!
//! 而且 tap 是**纯增益**：它挂不上或者解析不出来，最终结果照样从 stdout 拿得到，
//! 只是少了逐字流和工具展示。护栏不依赖它（见下）。
//!
//! # 护栏
//!
//! dsh 没有逐命令 deny 清单，只有三档沙箱，经 `DSH_PERMISSION_MODE` 环境变量注入，
//! 沙箱根 = 子进程的工作目录。见 [`dsh_permission_mode`]。
//!
//! # prompt 不进 argv
//!
//! dsh 的启动器**不认 `--` 作为选项终止符**（实测 `dsh --profile headless -- "--version"`
//! 会报 `unknown option '--version'`，不加 `--` 更糟：直接被当成启动器自己的 `--version`
//! 执行了）。所以任务文本一旦以 `-` 开头就会被劫持成 flag。
//!
//! 既然我们本来就要写 patch 文件，索性把 prompt 也从 argv 里彻底拿掉：patch 直接覆盖
//! `headless-runner` 的 `config.task`，argv 里只留一个固定的占位符。这样 prompt 既不会被
//! 解析成 flag，也不会出现在进程列表里——比另外三家都严。

use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::atomic::AtomicBool;
use std::sync::Arc;
use std::time::Duration;

use tokio::io::{AsyncBufReadExt, AsyncReadExt, BufReader};

use super::stream::CodingAgentEvent;
use super::{augmented_command, wait_cancel, CodingAgentEventSink, CodingAgentRequest};
use super::{CodingAgentError, CodingAgentPermissionMode};

/// argv 里那个固定占位任务。真正的 prompt 由 patch 覆盖 `headless-runner.config.task` 注入，
/// 但 `headless-startup` 仍要求 argv 上有个非空任务（空的话它会走 usage error 直接退出）。
pub const ARGV_TASK_PLACEHOLDER: &str = "openless-task";

/// 内嵌的 dsh-jsonl 插件版本。必须与 `vendor/dsh-jsonl.js` 头部的标记一致——
/// 下面的单测盯着这一点，防止有人直接改了 vendor 目录却没走同步流程。
pub const VENDORED_DSH_JSONL_VERSION: &str = "0.1.0";

/// 我们能解析的 dsh-jsonl schema 大版本。插件报的对不上只记警告，不中止——
/// 最终结果始终从 stdout 拿得到，流式展示只是锦上添花。
pub const SUPPORTED_DSH_JSONL_SCHEMA: u64 = 1;

/// 挂给 dsh 的输出插件，逐字内嵌自 [dsh-jsonl](https://github.com/bigsongeth/dsh-jsonl)。
///
/// **不要在这里改它。** 源头在那个仓库，这里只是一份带版本标记的副本，用
/// `scripts/vendor-dsh-jsonl.sh <checkout>` 同步。之所以内嵌而不是让 App 去依赖 npm 包：
/// 用户装机即用，不需要网络、不需要 `npm i`，也不会碰用户自己的 dsh profile 配置。
///
/// 跨仓库没有任何自动同步。忘了同步的后果是 OpenLess 停在旧版插件（照常工作），不是崩；
/// 真的对不上时 `live::tap_plugin_delivers_streaming_and_tool_events` 会红。
const TAP_PLUGIN_JS: &str = include_str!("vendor/dsh-jsonl.js");

/// 权限模式 → `DSH_PERMISSION_MODE` 取值。
///
/// dsh 的 `dsh-sandbox-policy` 插件读这个环境变量，沙箱根取子进程的工作目录
/// （`workspaceRoot: process.cwd()`）。三档语义与 Codex 的 `-s` 一致：
/// - `Plan` → `read-only`
/// - `Default` / `AcceptEdits` → `workspace-write`（默认档）
/// - `BypassPermissions` → `danger-full-access`（语音路径已在 dictation 层钳制掉）
pub fn dsh_permission_mode(mode: CodingAgentPermissionMode) -> &'static str {
    match mode {
        CodingAgentPermissionMode::Plan => "read-only",
        CodingAgentPermissionMode::Default | CodingAgentPermissionMode::AcceptEdits => {
            "workspace-write"
        }
        CodingAgentPermissionMode::BypassPermissions => "danger-full-access",
    }
}

/// 构造 `dsh` 的命令行参数（不含可执行文件本身，也不含 prompt——prompt 走 patch 文件）。
pub fn build_dsh_args(patch_path: &Path) -> Vec<String> {
    vec![
        "--profile".into(),
        "headless".into(),
        "--patch".into(),
        patch_path.to_string_lossy().into_owned(),
        // 占位任务：真正的 prompt 由 patch 覆盖 headless-runner.config.task。
        ARGV_TASK_PLACEHOLDER.into(),
    ]
}

/// 生成 `--patch` 的 YAML 内容：挂上 tap 插件 + 用真正的 prompt 覆盖 runner 的 task。
///
/// 路径和 prompt 都用 `serde_json::to_string` 序列化成带引号的字符串——JSON 字符串是合法的
/// YAML 双引号标量，转义规则也一致，所以换行、引号、反斜杠都能安全带过去，不用手搓转义。
pub fn build_dsh_patch_yaml(plugin_js_path: &Path, prompt: &str) -> Result<String, String> {
    let quoted_path = serde_json::to_string(&plugin_js_path.to_string_lossy())
        .map_err(|e| format!("序列化插件路径失败: {e}"))?;
    let quoted_task =
        serde_json::to_string(prompt).map_err(|e| format!("序列化任务文本失败: {e}"))?;
    // 必须用原始字符串：普通字符串字面量里的 `\` 换行续行会把下一行的**前导空格一起吃掉**，
    // YAML 的缩进全丢 → dsh 报 `failed to parse`。这条踩过，别改回续行写法。
    Ok(format!(
        r#"# Generated by OpenLess. Applied as the last patch layer for one headless run.
- insert:
    - id: dsh-jsonl
      name: {quoted_path}
- id: headless-runner
  config:
    task: {quoted_task}
"#
    ))
}

/// 解析一行 dsh-jsonl 输出的 NDJSON（schema v1，见插件仓库的 SCHEMA.md）。
///
/// 只认我们用得上的几种；**其余一律忽略**——这是 schema 的兼容性约定：消费者必须忽略
/// 自己不认识的 type 和字段，上游加新事件才不会把我们打挂。
///
/// dsh 自己往 stderr 打的普通日志（如 `dsh: <code>: <message>`）解析不出来，返回 `None`
/// 交给调用方另作处理。
pub fn parse_dsh_tap_line(session_id: &str, line: &str) -> Option<CodingAgentEvent> {
    let line = line.trim();
    if line.is_empty() {
        return None;
    }
    let v: serde_json::Value = serde_json::from_str(line).ok()?;
    // 没有信封就不是我们的行（dsh 的普通 stderr 日志也可能恰好是合法 JSON）。
    if v.get("v").is_none() {
        return None;
    }
    match v.get("type")?.as_str()? {
        "text.delta" => {
            let text = v.get("text")?.as_str()?.to_string();
            if text.is_empty() {
                return None;
            }
            Some(CodingAgentEvent::Delta {
                session_id: session_id.to_string(),
                text,
            })
        }
        "tool.call" => {
            let name = v.get("name")?.as_str()?.to_string();
            Some(CodingAgentEvent::ToolUse {
                session_id: session_id.to_string(),
                name,
            })
        }
        // 成功的终局由运行器在 EOF 处用 stdout 的最终文本合成，这里只管失败。
        "turn.end" => {
            if v.get("ok").and_then(serde_json::Value::as_bool) != Some(false) {
                return None;
            }
            let message = v
                .pointer("/error/message")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("dsh 本轮执行失败")
                .to_string();
            Some(CodingAgentEvent::Error {
                session_id: session_id.to_string(),
                message,
            })
        }
        _ => None,
    }
}

/// 插件报的 schema 大版本（来自 `session.start`）。与我们支持的对不上就该出声。
pub fn parse_dsh_schema_version(line: &str) -> Option<u64> {
    let v: serde_json::Value = serde_json::from_str(line.trim()).ok()?;
    if v.get("type")?.as_str()? != "session.start" {
        return None;
    }
    v.get("schema")?.as_u64()
}

/// 从 tap 的 `guard` 行里取出 dsh 自报的沙箱档位（用于日志取证：确认护栏真的生效了）。
pub fn parse_dsh_guard_line(line: &str) -> Option<String> {
    let v: serde_json::Value = serde_json::from_str(line.trim()).ok()?;
    if v.get("type")?.as_str()? != "guard" {
        return None;
    }
    v.get("sandbox")?.as_str().map(str::to_string)
}

/// 从子进程的 stderr 里挑一行最有信息量的做错误摘要。
///
/// 不能简单取最后一行：**Node 崩溃转储的最后一行是 `Node.js v24.19.0` 这样的版本号**，
/// 拿它当错误信息等于什么都没说（这条是踩过的坑，别改回 `.last()`）。优先级：
/// 1. dsh 自己的错误行（`dsh: <CODE>: <消息>`）——最准确；
/// 2. 第一行看起来像错误的（含 `Error` / `error:`）——Node 崩溃转储的抬头在最前面；
/// 3. 兜底取最后一条非空行。
fn summarize_stderr(lines: &[String]) -> String {
    let clean = |s: &String| s.trim().to_string();
    if let Some(l) = lines.iter().rev().find(|l| l.trim_start().starts_with("dsh:")) {
        return clean(l);
    }
    if let Some(l) = lines
        .iter()
        .find(|l| l.contains("Error") || l.contains("error:"))
    {
        return clean(l);
    }
    lines.last().map(clean).unwrap_or_default()
}

/// 一次运行用的临时目录：插件 JS + patch YAML。Drop 时整个删掉。
struct TapWorkspace {
    dir: PathBuf,
    patch_path: PathBuf,
}

impl TapWorkspace {
    /// 落盘 tap 插件与 patch 文件。prompt 会写进 patch 文件，所以目录权限收到 0700。
    fn create(prompt: &str) -> Result<Self, String> {
        let dir = std::env::temp_dir().join(format!("openless-dsh-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).map_err(|e| format!("创建临时目录失败: {e}"))?;
        // prompt 是用户的原话，落在临时文件里；只有本人可读。
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = std::fs::set_permissions(&dir, std::fs::Permissions::from_mode(0o700));
        }
        let js_path = dir.join("dsh-jsonl.mjs");
        std::fs::write(&js_path, TAP_PLUGIN_JS).map_err(|e| format!("写 tap 插件失败: {e}"))?;
        let patch_path = dir.join("openless.patch.yml");
        std::fs::write(&patch_path, build_dsh_patch_yaml(&js_path, prompt)?)
            .map_err(|e| format!("写 patch 文件失败: {e}"))?;
        Ok(Self { dir, patch_path })
    }
}

impl Drop for TapWorkspace {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.dir);
    }
}

/// 无头跑一次 dsh：prompt 经 patch 注入，stdout 收最终文本，stderr 收 tap 的 NDJSON。
/// 支持取消与超时（都会 kill 子进程）。
pub async fn run_dsh_agent(
    exe: &str,
    req: CodingAgentRequest,
    sink: CodingAgentEventSink,
    cancel: Arc<AtomicBool>,
) -> Result<(), CodingAgentError> {
    // prompt 与 tap 插件落盘。失败即中止：不是因为护栏（护栏走 env，见下），而是因为
    // prompt 本身就在这个文件里——写不出来就没有任务可跑。
    let workspace = TapWorkspace::create(&req.prompt).map_err(CodingAgentError::Io)?;

    let args = build_dsh_args(&workspace.patch_path);
    let mut cmd = augmented_command(exe);
    cmd.args(&args)
        // 护栏：沙箱档位。沙箱根 = 下面设的 current_dir。
        .env("DSH_PERMISSION_MODE", dsh_permission_mode(req.permission_mode))
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .kill_on_drop(true);
    if let Some(cwd) = &req.cwd {
        cmd.current_dir(cwd);
    }

    let mut child = cmd.spawn().map_err(|e| {
        if e.kind() == std::io::ErrorKind::NotFound {
            CodingAgentError::ExecutableNotFound(exe.to_string())
        } else {
            CodingAgentError::Spawn(e.to_string())
        }
    })?;

    // stdout = dsh 自己的最终文本（它稳定的对外契约），后台整篇读完。
    let stdout = child
        .stdout
        .take()
        .ok_or_else(|| CodingAgentError::Io("子进程无 stdout".into()))?;
    let stdout_task = tokio::spawn(async move {
        let mut buf = String::new();
        let _ = BufReader::new(stdout).read_to_string(&mut buf).await;
        buf
    });

    let stderr = child
        .stderr
        .take()
        .ok_or_else(|| CodingAgentError::Io("子进程无 stderr".into()))?;
    let mut lines = BufReader::new(stderr).lines();

    let _ = sink.send(CodingAgentEvent::Started {
        session_id: req.session_id.clone(),
    });

    let deadline = tokio::time::Instant::now() + Duration::from_secs(req.timeout_secs.max(1));
    let mut accumulated = String::new();
    // dsh 自己打到 stderr 的非 JSON 行：失败时拿来做错误摘要。
    let mut plain_stderr: Vec<String> = Vec::new();
    let mut saw_tap = false;
    let mut got_error = false;
    let mut outcome: Result<(), CodingAgentError> = Ok(());

    loop {
        tokio::select! {
            biased;
            _ = wait_cancel(&cancel) => {
                let _ = child.start_kill();
                let _ = sink.send(CodingAgentEvent::Cancelled { session_id: req.session_id.clone() });
                outcome = Err(CodingAgentError::Cancelled);
                break;
            }
            _ = tokio::time::sleep_until(deadline) => {
                let _ = child.start_kill();
                let _ = sink.send(CodingAgentEvent::Error {
                    session_id: req.session_id.clone(),
                    message: format!("运行超时（{}s）", req.timeout_secs),
                });
                got_error = true;
                outcome = Err(CodingAgentError::Timeout(req.timeout_secs));
                break;
            }
            line = lines.next_line() => {
                match line {
                    Ok(Some(l)) => {
                        // 取证：确认 dsh 真的按我们给的档位起了沙箱，而不是我们以为它起了。
                        if let Some(sandbox) = parse_dsh_guard_line(&l) {
                            saw_tap = true;
                            log::info!("[dsh] 沙箱档位 = {sandbox}");
                            continue;
                        }
                        if let Some(ev) = parse_dsh_tap_line(&req.session_id, &l) {
                            saw_tap = true;
                            match &ev {
                                CodingAgentEvent::Delta { text, .. } => accumulated.push_str(text),
                                CodingAgentEvent::Error { .. } => got_error = true,
                                _ => {}
                            }
                            let _ = sink.send(ev);
                        } else if let Some(schema) = parse_dsh_schema_version(&l) {
                            saw_tap = true;
                            if schema != SUPPORTED_DSH_JSONL_SCHEMA {
                                // 插件 schema 大版本变了 = 破坏性变更。任务照跑（结果仍从
                                // stdout 拿），但流式/工具展示可能不完整，留个声明性日志。
                                log::warn!(
                                    "[dsh] 插件 schema v{schema} 与本版支持的 v{SUPPORTED_DSH_JSONL_SCHEMA} 不一致，本轮流式展示可能不完整"
                                );
                            }
                        } else if l.trim_start().starts_with("{\"v\":") {
                            // 认识信封但不是我们关心的类型：按 schema 约定忽略。
                            saw_tap = true;
                        } else if !l.trim().is_empty() {
                            plain_stderr.push(l);
                        }
                    }
                    Ok(None) => break, // EOF：正常结束
                    Err(e) => {
                        outcome = Err(CodingAgentError::Io(e.to_string()));
                        break;
                    }
                }
            }
        }
    }

    let status = child
        .wait()
        .await
        .map_err(|e| CodingAgentError::Io(e.to_string()))?;
    let stdout_text = stdout_task.await.unwrap_or_default();

    if !plain_stderr.is_empty() {
        // 失败定位全靠这段：摘要只有一行，真正的因果常在崩溃转储的中间。
        let tail: Vec<&str> = plain_stderr.iter().rev().take(20).map(String::as_str).collect();
        log::debug!("[dsh] stderr 尾部（倒序）: {tail:?}");
    }

    if !saw_tap && outcome.is_ok() {
        // tap 没挂上（多半是 dsh 升级改了插件加载或事件形状）。任务照跑不误——最终文本
        // 还在 stdout——只是这一轮没有逐字流和工具展示。留日志便于事后定位。
        log::warn!("[dsh] tap 插件没有产出任何事件：本轮无逐字流/工具展示，最终结果仍取自 stdout");
    }

    if outcome.is_ok() {
        if status.success() && !got_error {
            // 最终文本优先取 stdout（dsh 稳定契约）；tap 挂了就退回累计的 delta。
            let text = if stdout_text.trim().is_empty() {
                accumulated.trim().to_string()
            } else {
                stdout_text.trim().to_string()
            };
            let _ = sink.send(CodingAgentEvent::Completed {
                session_id: req.session_id.clone(),
                text,
                cost_usd: None,
                duration_ms: None,
            });
            return Ok(());
        }
        if !status.success() && !got_error {
            let summary = summarize_stderr(&plain_stderr);
            let _ = sink.send(CodingAgentEvent::Error {
                session_id: req.session_id.clone(),
                message: if summary.is_empty() {
                    format!("agent 异常退出 (code={:?})", status.code())
                } else {
                    summary
                },
            });
            return Err(CodingAgentError::ProcessExit(status.code()));
        }
    }

    outcome
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn run_args_target_headless_profile_with_our_patch() {
        let args = build_dsh_args(Path::new("/tmp/x/openless.patch.yml"));
        assert_eq!(args[0], "--profile");
        assert_eq!(args[1], "headless");
        assert_eq!(args[2], "--patch");
        assert_eq!(args[3], "/tmp/x/openless.patch.yml");
        // argv 末尾只有占位任务。
        assert_eq!(args.last().map(|s| s.as_str()), Some(ARGV_TASK_PLACEHOLDER));
    }

    #[test]
    fn prompt_never_enters_argv() {
        // 关键不变量：dsh 的启动器不认 `--` 作为选项终止符（实测），所以 prompt 一旦进
        // argv，以 `-` 开头的转写就会被劫持成 flag。prompt 只能走 patch 文件。
        let args = build_dsh_args(Path::new("/tmp/x/p.yml"));
        assert!(!args.iter().any(|a| a.contains("危险的原话")));
        assert_eq!(args.len(), 5, "argv 只应有 profile/patch/占位任务，多一个都可疑");
    }

    #[test]
    fn patch_is_byte_exact_including_indentation() {
        // 逐字比对而不是 contains：YAML 全靠缩进，缩进丢了 dsh 直接 `failed to parse`，
        // 而 contains 完全看不出来（这就是当初漏掉的那个 bug）。
        let yaml =
            build_dsh_patch_yaml(Path::new("/tmp/x/dsh-jsonl.mjs"), "读一下 a.txt").unwrap();
        let expected = concat!(
            "# Generated by OpenLess. Applied as the last patch layer for one headless run.\n",
            "- insert:\n",
            "    - id: dsh-jsonl\n",
            "      name: \"/tmp/x/dsh-jsonl.mjs\"\n",
            "- id: headless-runner\n",
            "  config:\n",
            "    task: \"读一下 a.txt\"\n",
        );
        assert_eq!(yaml, expected);
    }

    #[test]
    fn patch_quotes_hostile_prompts_safely() {
        // 转写里出现引号 / 换行 / 反斜杠 / YAML 结构字符时，不能把 patch 文件写坏
        // ——写坏了轻则跑不起来，重则 prompt 的一部分被当成 YAML 结构解释。
        let nasty = "他说\"删掉\"\n- id: headless-runner\n  config:\n    task: 被劫持了\\";
        let yaml = build_dsh_patch_yaml(Path::new("/tmp/x/t.mjs"), nasty).unwrap();
        // 整个 prompt 必须是单行的双引号标量：换行被转义成 \n，不会另起一行。
        let task_lines: Vec<&str> = yaml.lines().filter(|l| l.contains("task:")).collect();
        assert_eq!(task_lines.len(), 1, "task 必须压成一行，不能被换行撑开");
        assert!(task_lines[0].contains("\\n"), "换行必须转义");
        assert!(task_lines[0].contains("\\\""), "引号必须转义");
        // 被劫持的那一行不能作为独立的 YAML 行出现。
        assert!(!yaml.lines().any(|l| l.trim() == "task: 被劫持了\\"));
    }

    #[test]
    fn permission_mode_maps_to_env_value() {
        assert_eq!(
            dsh_permission_mode(CodingAgentPermissionMode::Plan),
            "read-only"
        );
        assert_eq!(
            dsh_permission_mode(CodingAgentPermissionMode::AcceptEdits),
            "workspace-write"
        );
        assert_eq!(
            dsh_permission_mode(CodingAgentPermissionMode::Default),
            "workspace-write"
        );
        assert_eq!(
            dsh_permission_mode(CodingAgentPermissionMode::BypassPermissions),
            "danger-full-access"
        );
    }

    #[test]
    fn vendored_plugin_version_matches_the_constant() {
        // 防的是「有人直接改了 vendor/dsh-jsonl.js 却没走 scripts/vendor-dsh-jsonl.sh」。
        // 跨仓库没有自动同步，这条是唯一能当场发现副本被手改的地方。
        let marker = format!("dsh-jsonl v{VENDORED_DSH_JSONL_VERSION}");
        assert!(
            TAP_PLUGIN_JS.lines().next().unwrap_or("").contains(&marker),
            "vendor/dsh-jsonl.js 首行的版本标记与 VENDORED_DSH_JSONL_VERSION 对不上；\
             跑 scripts/vendor-dsh-jsonl.sh 重新同步，并把常量改成一致"
        );
        assert!(
            TAP_PLUGIN_JS.contains("do not edit here"),
            "vendor 文件缺少「别在这儿改」的头部标记"
        );
    }

    #[test]
    fn vendored_plugin_needs_no_node_modules_and_leaves_stdout_alone() {
        // 插件从临时目录以绝对路径加载，身边**没有 node_modules**：任何裸包名 import
        // 都会加载失败。`node:` 开头的内置模块不受影响，所以只禁裸导入。
        for line in TAP_PLUGIN_JS.lines() {
            let line = line.trim();
            if line.starts_with("import ") {
                assert!(
                    line.contains("'node:") || line.contains("\"node:"),
                    "插件只能 import node: 内置模块（身边没有 node_modules）: {line}"
                );
            }
            assert!(!line.contains("require("), "插件不能有 require: {line}");
        }
        // stdout 属于 dsh 的最终文本；插件默认写 stderr（`DSH_JSONL_OUT=stdout` 是用户
        // 自己显式选的，OpenLess 不会设它）。
        assert!(TAP_PLUGIN_JS.contains("process.stderr"));
        // 订阅点就是这一个。
        assert!(TAP_PLUGIN_JS.contains("session/event"));
    }

    #[test]
    fn parses_delta_and_tool_and_guard() {
        // 形状取自 dsh-jsonl schema v1（真实抓取的样本）。
        assert_eq!(
            parse_dsh_tap_line(
                "s1",
                r#"{"v":1,"seq":36,"ts":1,"type":"text.delta","turn":1,"step":3,"index":0,"text":"你好"}"#
            ),
            Some(CodingAgentEvent::Delta {
                session_id: "s1".into(),
                text: "你好".into()
            })
        );
        assert_eq!(
            parse_dsh_tap_line(
                "s1",
                r#"{"v":1,"seq":20,"ts":1,"type":"tool.call","callId":"c1","name":"glob","arguments":"{}"}"#
            ),
            Some(CodingAgentEvent::ToolUse {
                session_id: "s1".into(),
                name: "glob".into()
            })
        );
        assert_eq!(
            parse_dsh_guard_line(
                r#"{"v":1,"seq":2,"ts":1,"type":"guard","sandbox":"workspace-write","approval":"ask"}"#
            ),
            Some("workspace-write".to_string())
        );
        assert_eq!(
            parse_dsh_schema_version(
                r#"{"v":1,"seq":0,"ts":null,"type":"session.start","sessionId":"s","cwd":"/tmp","schema":1}"#
            ),
            Some(SUPPORTED_DSH_JSONL_SCHEMA)
        );
    }

    #[test]
    fn unknown_event_types_are_ignored_not_fatal() {
        // schema 的兼容性约定：消费者必须忽略不认识的 type。上游加新事件不能把我们打挂。
        for line in [
            r#"{"v":1,"seq":1,"ts":1,"type":"step.start","turn":1,"step":1}"#,
            r#"{"v":1,"seq":2,"ts":1,"type":"usage","inputTokens":1,"outputTokens":2}"#,
            r#"{"v":1,"seq":3,"ts":1,"type":"something.invented.later","x":1}"#,
            r#"{"v":2,"seq":4,"ts":1,"type":"text.delta","text":"未来版本"}"#,
        ] {
            // 前三条是「不关心」，最后一条是「大版本变了」——都不该 panic。
            let _ = parse_dsh_tap_line("s1", line);
        }
    }

    #[test]
    fn successful_end_is_not_an_event_but_failure_is() {
        // 成功终局由运行器用 stdout 合成，tap 的 end 不再重复抛一次。
        assert_eq!(
            parse_dsh_tap_line("s1", r#"{"v":1,"seq":9,"ts":1,"type":"turn.end","turn":1,"ok":true}"#),
            None
        );
        assert_eq!(
            parse_dsh_tap_line(
                "s1",
                r#"{"v":1,"seq":9,"ts":1,"type":"turn.end","turn":1,"ok":false,"error":{"code":"PI_AI_ERROR","message":"上游超时"}}"#
            ),
            Some(CodingAgentEvent::Error {
                session_id: "s1".into(),
                message: "上游超时".into()
            })
        );
        // 失败但没给文案时也要有话说。
        assert_eq!(
            parse_dsh_tap_line("s1", r#"{"v":1,"seq":9,"ts":1,"type":"turn.end","turn":1,"ok":false}"#),
            Some(CodingAgentEvent::Error {
                session_id: "s1".into(),
                message: "dsh 本轮执行失败".into()
            })
        );
    }

    #[test]
    fn ignores_dsh_own_stderr_and_garbage() {
        // dsh 自己的错误行不是我们的协议，交给调用方当纯文本处理。
        assert_eq!(
            parse_dsh_tap_line("s1", "dsh: E_UPSTREAM: something broke"),
            None
        );
        // 没有信封的 JSON 不是我们的行。
        assert_eq!(parse_dsh_tap_line("s1", r#"{"type":"text.delta","text":"x"}"#), None);
        assert_eq!(parse_dsh_tap_line("s1", "not json"), None);
        assert_eq!(parse_dsh_tap_line("s1", ""), None);
        assert_eq!(parse_dsh_guard_line(r#"{"v":1,"type":"text.delta","text":"x"}"#), None);
    }

    #[test]
    fn tap_workspace_writes_both_files_and_cleans_up() {
        let dir = {
            let ws = TapWorkspace::create("跑个测试").unwrap();
            assert!(ws.patch_path.exists(), "patch 文件应已落盘");
            assert!(
                ws.dir.join("dsh-jsonl.mjs").exists(),
                "tap 插件应已落盘"
            );
            let yaml = std::fs::read_to_string(&ws.patch_path).unwrap();
            assert!(yaml.contains("跑个测试"));
            ws.dir.clone()
        };
        // Drop 之后临时目录必须消失：里面有用户原话。
        assert!(!dir.exists(), "TapWorkspace drop 后临时目录应被删除");
    }
}

/// 打真实 `dsh` CLI 的联机验收。默认 `#[ignore]`——要花钱、要网络、要本机装了 dsh。
/// 手动跑：`cargo test --lib coding_agent::dsh::live -- --ignored --nocapture --test-threads=1`
#[cfg(test)]
mod live {
    use super::*;
    use std::sync::atomic::AtomicBool;

    fn fixture_dir() -> PathBuf {
        let dir = std::env::temp_dir().join(format!("openless-live-dsh-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("a.txt"), "hello\n").unwrap();
        dir
    }

    struct Collected {
        tools: Vec<String>,
        deltas: usize,
        completed: Option<String>,
        error: Option<String>,
    }

    async fn run(prompt: &str, dir: &Path, mode: CodingAgentPermissionMode) -> Collected {
        let mut req = CodingAgentRequest::new("live", prompt.to_string());
        req.cwd = Some(dir.to_path_buf());
        req.permission_mode = mode;
        req.timeout_secs = 300;
        let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel();
        let cancel = Arc::new(AtomicBool::new(false));
        let handle = tokio::spawn(async move { run_dsh_agent("dsh", req, tx, cancel).await });
        let mut c = Collected {
            tools: Vec::new(),
            deltas: 0,
            completed: None,
            error: None,
        };
        while let Some(ev) = rx.recv().await {
            match ev {
                CodingAgentEvent::ToolUse { name, .. } => c.tools.push(name),
                CodingAgentEvent::Delta { .. } => c.deltas += 1,
                CodingAgentEvent::Completed { text, .. } => c.completed = Some(text),
                CodingAgentEvent::Error { message, .. } => c.error = Some(message),
                _ => {}
            }
        }
        let _ = handle.await;
        c
    }

    #[tokio::test]
    #[ignore = "打真实 dsh CLI：要花钱、要网络"]
    async fn tap_plugin_delivers_streaming_and_tool_events() {
        // 这条同时验收三件事：任务跑通、tap 插件挂上了（有 delta）、工具调用能看见。
        // delta 数 > 0 是 tap 生效的硬证据——不挂插件的话 dsh 只在最后吐一行，一个 delta 都没有。
        let dir = fixture_dir();
        let c = run(
            "读一下当前目录的 a.txt，然后只回答文件里的那个单词，不要解释。",
            &dir,
            CodingAgentPermissionMode::AcceptEdits,
        )
        .await;
        println!(
            "[dsh] tools={:?} deltas={} completed={:?} error={:?}",
            c.tools, c.deltas, c.completed, c.error
        );
        assert!(c.error.is_none(), "不应报错: {:?}", c.error);
        assert!(c.deltas > 0, "tap 插件没产出逐字流：说明它没挂上或事件形状变了");
        assert!(!c.tools.is_empty(), "应至少有一次工具调用（读文件）");
        let text = c.completed.expect("应有终局文本");
        assert!(text.to_lowercase().contains("hello"), "终局文本应含 hello，实际: {text}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    #[ignore = "打真实 dsh CLI：要花钱、要网络"]
    async fn sandbox_blocks_writes_outside_the_workspace() {
        // 同 codex：断言文件真的没出现，而不是信模型的自述。
        let dir = fixture_dir();
        let victim =
            std::env::temp_dir().join(format!("openless-dsh-escape-{}.txt", uuid::Uuid::new_v4()));
        let c = run(
            &format!(
                "在 {} 这个绝对路径创建一个文件，内容写 pwned。做完只回答 DONE 或 BLOCKED。",
                victim.display()
            ),
            &dir,
            CodingAgentPermissionMode::AcceptEdits,
        )
        .await;
        println!("[dsh] 越权写入结果 completed={:?} error={:?}", c.completed, c.error);
        assert!(!victim.exists(), "沙箱失效：工作目录外的文件被创建了 {}", victim.display());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    #[ignore = "打真实 dsh CLI：要花钱、要网络"]
    async fn prompt_starting_with_a_dash_is_not_parsed_as_a_flag() {
        // 回归防线：dsh 的启动器不认 `--`，prompt 一旦进 argv，这条会被当成 `--version` 执行，
        // 输出变成版本号。走 patch 注入才不会。
        let dir = fixture_dir();
        let c = run(
            "--version 这不是一个命令行参数。请忽略它的字面含义，只回答四个字：参数没跑。",
            &dir,
            CodingAgentPermissionMode::AcceptEdits,
        )
        .await;
        println!("[dsh] 参数注入用例 completed={:?} error={:?}", c.completed, c.error);
        let text = c.completed.expect("应有终局文本");
        assert!(
            !text.trim().starts_with("0."),
            "prompt 被当成 --version 执行了，输出是版本号: {text}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }
}
